### ISSUE TITLE
Syntax Highlighting for error messages

### ISSUE THREAD

**Issue by rtfeldman** [eeue56/elm-html-test#1]
As @eeue56 suggested, it would be sweet if the HTML in the error messages had syntax highlighting.

I think this could be even more valuable if we highlighted the matches in the subsequent query. For example, say we have this pipeline:

```elm
someHtml
    |> Query.fromHtml
    |> Query.findAll [ tag "img" ]
    |> Query.count (Expect.equal 5)
```

If this test fails, we could do normal syntax highlighting on the `Query.fromHtml` output, but also add something visually distinctive (e.g. a slightly lighter background, so they appear "highlighted" like search results) on the `img` elements, because those are what the next query will match.

This way if I'm looking at the output of the `Query.findAll [ tag "img" ]` part and I see 6 matches instead of the expected 5, I can ask "wait, where did the sixth `img` come from?" and can scroll up to look at the highlighted `img`s in the previous step's output to answer my question.

**Comment by eeue56** [comment]
Closing as this is currently not possible with elm-test. Will reopen/examine when it is
