### ISSUE TITLE
Error internally processing HTML for testing: Expecting an object with a field named `type` but instead got: undefined

### ISSUE THREAD

**Issue by avh4** [eeue56/elm-html-test#34]
I got the following error in a new test:

```
    This test failed because it threw an exception: "Error: Ran into a `Debug.crash` in module `Html.Inert`

    This was caused by the `case` expression between lines 19 and 24.
    One of the branches ended with a crash and the following value got through:

        Err "Expecting an object with a field named `type` at _.children[1].children[0].children[5].children[0].children[0].children[1].children[0].children[1].children[0].children[0].children[1].children[0]._1.node but instead got: undefined"

    The message provided by the code author is:

        Error internally processing HTML for testing - please report this error message as a bug: Expecting an object with a field named `type` at _.children[1].children[0].children[5].children[0].children[0].children[1].children[0].children[1].children[0].children[0].children[1].children[0]._1.node but instead got: undefined"
```

What info is useful for debugging this?

**Comment by avh4** [comment]
I am finding an element with `findAll [ ... ] >> Query.first` ... there are three nodes that match the findAll, but if I do `Query.index 1` or `2` instead of `first` or `index 0`, then it complains that it doesn't find any matches.

If I use `first`, then I try to simulate an event on the found node, and get the error in the original post.

**Comment by eeue56** [comment]
Hmm. Seems like some edge case in the decoder, perhaps. Does this view you're testing contain a lazy or keyed view?

**Comment by avh4** [comment]
no lazy, but it does contain keyed views, though I think the keyed views are all within a node that's below the ones selected here...

**Comment by eeue56** [comment]
Someone else reported this issue on Slack the other day: https://elmlang.slackarchive.io/general/page-46/ts-1496746323110540

A SSCCE would be extremely appreciated here

**Comment by eeue56** [comment]
I'm assuming it is something to do with the exact setup of view that you have

**Comment by avh4** [comment]
I originally thought this maybe had to do with simulating an event or finding the node to simulate on; but it turns out this error happens for use *after* that particular event is processed; so the problem seems to be in some HTML that appears after we expand a collapsed section.  That section does include Keyed, so maybe it's related to that.

(Sorry, no time for SSCCE yet)

**Comment by stoeffel** [comment]
> no lazy, but it does contain keyed views, though I think the keyed views are all within a node that's below the ones selected here...

We actually use elm-sortable-table in that view, which uses lazy.

**Comment by stoeffel** [comment]
So this fails because of this structure.
```
{ ctor: '_Tuple2',
  _0: '8168233',
  _1:
   { type: 'thunk',
     func: { [Function: wrapper] arity: 3, func: [Function] },
     args:
      [ [Object],
        [Function: _evancz$elm_sortable_table$Table$simpleRowAttrs],
        [Object] ],
     thunk: [Function],
     node: undefined } }
```
This node is created here https://github.com/evancz/elm-sortable-table/blob/master/src/Table.elm#L431. It's a keyed node and the children are lazy https://github.com/evancz/elm-sortable-table/blob/master/src/Table.elm#L482.

The easiest solution is to change the native code in this module:

```diff
var _eeue56$elm_html_test$Native_HtmlAsJson = (function() {
  function forceThunks(vNode) {
+    if (
+     typeof vNode !== "undefined" && vNode.ctor === "_Tuple2" && !vNode.node
+   ) {
+     vNode._1 = forceThunks(vNode._1);
    }
    if (typeof vNode !== "undefined" && vNode.type === "thunk" && !vNode.node) {
      vNode.node = vNode.thunk.apply(vNode.thunk, vNode.args);
    }
    if (typeof vNode !== "undefined" && typeof vNode.children !== "undefined") {
      vNode.children = vNode.children.map(forceThunks);
    }
    return vNode;
  }

  return {
    toJson: function(html) {
      return forceThunks(html);
    },
    eventDecoder: function(event) {
      return event.decoder;
    },
    taggerFunction: function(tagger) {
      return tagger;
    }
  };
})();
```
sorry prettier formatted that code.

**Comment by avh4** [comment]
vNodes for keyed children are tuples?  If that's how it's supposed to be, then I think the suggested code looks good.

**Comment by eeue56** [comment]
Yep, they are meant to be tuples: https://github.com/elm-lang/virtual-dom/blob/master/src/Native/VirtualDom.js#L852

I would prefer we had this represented correctly in elm-html-in-elm: https://github.com/eeue56/elm-html-in-elm/blob/master/src/ElmHtml/InternalTypes.elm#L277

I think it would be better to store the key as well as the evaluated child

**Comment by stoeffel** [comment]
@eeue56 I can make a PR, if you want me to?
