### ISSUE TITLE
Query.contains error when using onInput

### ISSUE THREAD

**Issue by yormi** [eeue56/elm-html-test#37]
> This test failed because it threw an exception: "Error: Trying to use `(==)` on functions. There is no way to know if functions are "the same" in the Elm sense. Read more about this at http://package.elm-lang.org/packages/elm-lang/core/latest/Basics#== which describes why it is this way and what the better version will look like."

After few tests to reproduce the problem, that seems to happen only if we use a function with arguments to render some Html that has a `Events.onInput (\a -> a)` in it.

Oddly enough, there's not error when we use a message that only has a String like when you replace the `(A "a")` by `B` in the following:

So, here's the test I used in `tests/Descendant.elm` :

```elm
            test "works with function rendering onInput with a function as argument" <|
                \() ->
                    let
                        htmlWithEvent notEvenUsed =
                            div [] [ h1 [ onInput (A "a") ] [] ]

                        html =
                            div [] [ htmlWithEvent "foo" ]
                    in
                        wrapper html (htmlWithEvent "foo")
                            |> Expect.true ""

type Msg
    = A String String
    | B String
```

Do you have an idea why on Earth it does that under such conditions ?

I'll be gone for almost 2 weeks. I'd like to solve that when I'll come back :)

**Comment by yormi** [comment]
Ok so after some digging, the same happens with `onCheck`. They are the only 2 that have a function as first argument.

`onCheck : (Bool -> msg) -> Attribute msg`
`onInput : (String -> msg) -> Attribute msg`

The thing I don't get is why having a parameter to the specific view function will change the behavior. I guess it's lazy-evaluation related but I'm not sure what we can do about it yet.

**Comment by zwilias** [comment]
Cross-posting from elm-lang/virtual-dom#113:

> Equality in Elm on functions only "works" when dealing with referential equality.
>
> Because of eager evaluation, you end up with the same event handler in the case where your html-producing takes no arguments. Similarly, if the event mapping function is simply A, it's referentially equal to another A. By having a parameter on your html-producing function - even if you actually ignore it - evaluation doesn't happen until all arguments are passed, so you'll end up with two separate (\s -> A s) functions that are not referentially equal.
>
> Note that this is not a virtual-dom issue and expected behaviour.

---

The core issue is indeed an equality check on 2 functions that are not referentially equal. If you could show the original code where you ran into this in the context of `elm-html-test`, we can further attempt to investigate, and try to come up with a workaround or a constructive fix, depending on the particulars.

**Comment by yormi** [comment]
Thank you for taking the time :)

Ok so the problem is just that I want to check if some html, `child` is contained in some other html, `parent`. Right now, the code for that recursively check equality between `child` and `parent`'s children. https://github.com/eeue56/elm-html-test/blob/master/src/Test/Html/Descendant.elm#L15

A quick workaround would be to replace the `EVENT` record of the node by an empty one. Then adding in the doc that events are not compared when using `Query.contains`.

What do you think about this workaround ?
Any better idea 'cause I feel a  bit dirty with mine ?

How are the html compared when diffing for rendering ?

**Comment by zwilias** [comment]
That happens in native land, where equality has a different meaning altogether :)

Comparing descendants while dealing with event-handlers is tricky. In most cases, you simply wouldn't run into this, and I think entirely dropping comparison of event handlers isn't really worth it.. I wonder if it makes sense to allow both to coexist; strict equality as the default, and handler-ignore equality if you need it, with the caveat that it would consider `input [ onInput Foo ] []` and `input [ onInput Bar ] []` equal.

**Comment by yormi** [comment]
Oh I see ! I don't want to go to native land :p 

It seems to me that it'll be error prone if you rely on your test to check event-handling and some times it won't because 2 weeks ago you had a flag so it won't check it.

When I added the `contains` feature it was to check that a composed view-function (like `menuView`) was rendering a sub-view (like `menuButton "Home"`). Do you think there's something to do with [Html.Lazy](http://package.elm-lang.org/packages/elm-lang/html/2.0.0/Html-Lazy) ? When I used it, I got the "function equality error" but if it just check the function + the arguments, it should work, shouldn't it ?

**Comment by rtfeldman** [comment]
Thanks for reporting this, and for the discussion! Now that it's clearer what the problem is, I opened https://github.com/eeue56/elm-html-test/issues/50 to discuss solutions.
