### ISSUE TITLE
some way to find an element in relation to another element

### ISSUE THREAD

**Issue by avh4** [eeue56/elm-html-test#53]
Split from https://github.com/eeue56/elm-html-test/issues/32 by request.

some way to find an element in relation to another element.  In this example, find the button in "Section A" (and ignore the button in "Section B"):

```elm
div []
    [ section []
        [ h3 [] [ text "Section A" ]
        , button [] [ text "Submit" ]
        ]
    , section []
        [ h3 [] [ text "Section B" ]
        , button [] [ text "Submit" ]
        ]
    ]
```

Possible API:
```elm
Query.find
    [ tag "section"
    , havingChild [ tag "h3", text "Section A" ]
    ]
    |> Query.find [ tag "button", text "Submit" ]
```

Another possible API:
```elm
Query.find
    [ tag "button"
    , text "Submit"
    , havingAncestor [ tag "section", text "Section A" ]
    ]
```

**Comment by rtfeldman** [comment]
I like the idea of a variation on the first API that works on descendants instead of children, and calling it `containing` instead of `havingChild` - [more notes on why here](https://github.com/eeue56/elm-html-test/pull/47#pullrequestreview-93824878).
