### ISSUE TITLE
Would love a `Query.hasNot`

### ISSUE THREAD

**Issue by brookeangel** [eeue56/elm-html-test#8]
Currently I've been doing some workarounds to see if a `Selector` does not appear in a `Single`. Would love a `Query.hasNot` function with the same type signature as `Query.has`. Thanks!

**Comment by eeue56** [comment]
If you're interested in trying to implement it yourself, [here's](https://github.com/eeue56/elm-html-test/blob/master/src/Test/Html/Query/Internal.elm#L406) the code for `has`. Switching it to `hasNot` should just be a case of making the same function with the logic flipped, and then expose it like [this](https://github.com/eeue56/elm-html-test/blob/master/src/Test/Html/Query.elm#L311)

**Comment by eeue56** [comment]
This is closed by #9 - I'll publish it when your other PR to fix the children comes it :)
